### ISSUE TITLE
WAS ratio is based on the median, not the average

### ISSUE THREAD

**Issue by mherrmann3** [RoboticMind/Project-Whitelist-Checker#1]
As described on [gridcoin.us/wiki/whitelist-process.html](https://gridcoin.us/wiki/whitelist-process.html#criteria-for-being-considered), the WAS is defined as the ratio of the **median** of the last 7-day and last 40-day credits.

If the credits-per-day are more or less constant, it can indeed be approximated with the average. But as soon as the credits-per-day fluctuate strongly, the average and median will start to differ. Especially if zero-credit days are involved, the median may behave completely different: imagine if 21 days have zero credit. Then, the 40-day-median will be also zero and the WAS ratio undefined (division by zero), i.e.., not > 0.1 (green).[^1]

[^1]: This special case is somehow a **hidden third criteria** in the white/graylist definition: a project must have less than 21 zero-credit days to be whitelisted. So if you cannot implement the median, you may at least check for this special case.

**Comment by RoboticMind** [comment]
Oh oops that's actually an error in the documentation. (I would know, I also wrote the documentation) 

The original definition was defined as

> `WAS = Green If (Mean daily credit for 7 Days > (0.1 * Mean daily credit for 40 Days)) Else Red`

https://github.com/gridcoin-community/Gridcoin-Tasks/issues/194

Dividing the two gives you

`Mean daily credit for 7 Days / Mean daily credit for 40 Days > 0.1`

I did later notice that the original definition does avoid the division by zero issue edge case, however it also fails the ZCD check when that happens so I wasn't too concerned

**Comment by RoboticMind** [comment]
PR has now been put up to fix the documentation on the gridcoin.us site

https://github.com/gridcoin-community/Gridcoin-Site/pull/426
